name: Build Ren'Py Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Ren'Py
      run: |
        sudo apt-get update
        sudo apt-get install -y renpy

    - name: Build Ren'Py Project
      run: |
        renpy .

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: renpy-build
        path: ./build

