name: Build Ren'Py Project

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ren'Py
      uses: renpy/renpy-setup-action@v1
      with:
        version: '7.4.11' # Specify the version of Ren'Py to use

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wine-stable

    - name: Build game for Windows
      run: |
        ./renpy/renpy.sh launcher distribute .
        mkdir -p build
        mv ./dist/* ./build/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: renpy-windows-build
        path: build/
