name: Lint RenPy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install RenPy
      uses: PaxlavaGames/renpy-install@v0.2.0
      with:
        version: "8.2.0"
    - name: Lint RenPy
      uses: PaxlavaGames/renpy-lint@0.4.0
      with:
        path: "./testing"
